name: mda-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - pytest
  - python==3.7
  - MDAnalysis>=2.0.0
  - MDAnalysisTests>=2.0.0
  - coverage[toml]
  - pytest
  - pytest-cov
  - hypothesis
