package:
  name: mdacli
  version: "0.1.12"

source:
   git_url: https://github.com/MDAnalysis/mdanalysis
   # git_branch: develop
   git_tag: v0.1.12

# specify the subversion of the conda package. Defaults to 0. If you make
# changes to the conda package alone with out an increase in the source package
# version increase this number. Should be reset to 0 after a new release
build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - MDAnalysis

about:
  home: https://www.mdanalysis.org
  license: GPLv2
  license_file: package/LICENSE
  summary: 'MDAnalysis is a Python library to analyze molecular dynamics trajectories.'
