# tests required for Pull Requests
# but should not run after push to master
name: PR Requirements

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install virtualenv tox

    # asserts developer added additions to CHANGELOG
    - name: Test CHANGELOG
      run: tox -e chlog
