name: foo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2

    - name: Activate conda on MacOS & Linux
    - if: runner.os != "Windows"
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge

    - name: Activate conda on Windows
    - if: runner.os == "Windows"
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ""
        python-version: ${{ matrix.python-version }}
        channels: conda-forge

    - name: Install dependencies
      run: conda install pip setuptools wheel virtualenv tox coverage[toml]

    - name: Fix Conda permissions on macOS
      if: runner.os == 'macOS'
      run: sudo chown -R $UID $CONDA

    - name: Test Python unittests
      run: tox -e test

    #from https://github.com/codecov/codecov-action
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        env_vars: OS,PYTHON
        files: ./coverage.xml
        fail_ci_if_error: true
        verbose: true
