name: Build and version bump

on:
  push:
    branches:
      - main

jobs:
  bump-version:

    runs-on: ubuntu-latest
    defaults:
       run:
         shell: bash -l {0}
    if: "!startsWith(github.event.head_commit.message, '[SKIP]')"

    steps:

    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.AC_GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup Git
      run: |
        git config user.name "joaomcteixeira"
        git config user.email 'joaomcteixeira@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.AC_GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"

    - name: Setup env variables
      run: |
        echo "SKIPBUMP=FALSE" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bump2version setuptools wheel twine

    # If a commit starts with [MAJOR] a new major verion upgrade will be
    # triggered. Use with caution as Major upgrades denote backwards
    # incompatibility. Yet I like it to be integrated in the CI
    - name: Bump Major Version
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}
      run: |
        bump2version minor
        echo "SKIPBUMP=TRUE" >> $GITHUB_ENV
      if: "startsWith(github.event.head_commit.message, '[MAJOR]')"

    - name: Bump Minor Version
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}
      run: |
        bump2version minor
        echo "SKIPBUMP=TRUE" >> $GITHUB_ENV
      if: "startsWith(github.event.head_commit.message, '[MINOR]')"

    # Default action
    - name: Bump Patch Version
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}
      run: |
        bump2version patch
      if: env.SKIPBUMP == 'FALSE'

    - name: Commit version change to main
      run: |
        git push --follow-tags

    - name: Build and publish to PYPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --verbose dist/*

    - uses: conda-incubator/setup-miniconda@v2
      with:
         activate-environment: ""
         auto-update-conda: true
         auto-activate-base: true
         channels: conda-forge

    - run: conda install conda-build anaconda-client

    - name: Build and publish to ANACONDA
      run: |
        conda-build .
        anaconda login --username ${{ secrets.CONDA_USER }} --password ${{ secrets.CONDA_PASS }}
        anaconda --verbose upload --all ~/miniconda/conda-bld/linux-64/*
